apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "task-api.fullname" . }}-config
  labels:
    {{- include "task-api.labels" . | nindent 4 }}
data:
  DB_HOST: {{ include "task-api.fullname" . }}-postgres
  DB_PORT: {{ .Values.env.DB_PORT | quote }}
  DB_NAME: {{ .Values.env.DB_NAME | quote }}
  DB_USER: {{ .Values.env.DB_USER | quote }}