apiVersion: v1
kind: Secret
metadata:
  name: {{ include "task-api.fullname" . }}-secret
  labels:
    {{- include "task-api.labels" . | nindent 4 }}
type: Opaque
stringData:
{{- range $key, $value := .Values.secretEnv }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
