apiVersion: v1
kind: Secret
metadata:
  name: {{ include "task-api.fullname" . }}-secret
  labels:
    {{- include "task-api.labels" . | nindent 4 }}
type: Opaque
stringData:
  DB_PASSWORD: {{ .Values.secretEnv.DB_PASSWORD | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgres.auth.password | quote }}