{{- if and .Values.secret.create .Values.secret.existingSecret }}
{{- fail "secret.existingSecret must be empty when secret.create is true" }}
{{- else if and (not .Values.secret.create) (not .Values.secret.existingSecret) }}
{{- fail "secret.existingSecret must be set when secret.create is false" }}
{{- end }}
{{- if .Values.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "task-api.fullname" . }}-secret
  labels:
    {{- include "task-api.labels" . | nindent 4 }}
type: Opaque
stringData:
{{- range $key, $value := .Values.secretEnv }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
{{- end }}
