# Default values for task-api.

replicaCount: 1

image:
  repository: task-api
  tag: "0.1.0"
  pullPolicy: Never

imagePullSecrets: []

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 8000
  targetPort: 8000

ingress:
  enabled: true
  className: ""
  annotations: {}
  hosts:
    - host: task-api.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

httpRoute:
  enabled: false
  annotations: {}
  parentRefs:
    - name: gateway
      sectionName: http
  hostnames:
    - chart-example.local
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /headers

resources: {}

livenessProbe:
  httpGet:
    path: /healthz
    port: http

readinessProbe:
  httpGet:
    path: /readyz
    port: http

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

volumes: []

volumeMounts: []

nodeSelector: {}

tolerations: []

affinity: {}

env:
  DB_PORT: "5432"
  DB_NAME: taskdb
  DB_USER: taskuser

secretEnv:
  DB_PASSWORD: taskpass

postgres:
  image:
    repository: postgres
    tag: "16"
  service:
    port: 5432
  auth:
    database: taskdb
    username: taskuser
    password: taskpass
  persistence:
    enabled: true
    size: 1Gi