name: task-api-ci-cd

on:
  push:
    branches:
      - feature/week6-cicd
      - main

permissions:
  id-token: write
  contents: read

jobs:
  build-push-update-gitops:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout application repository
        uses: actions/checkout@v4

      - name: Python syntax check
        run: python -m compileall app

      - name: Set image tag
        run: echo "IMAGE_TAG=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push Docker image
        run: |
          ECR_URI=${{ vars.AWS_ACCOUNT_ID }}.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com/${{ vars.ECR_REPOSITORY }}

          docker build -t $ECR_URI:$IMAGE_TAG .
          docker push $ECR_URI:$IMAGE_TAG

      - name: Checkout GitOps repository
        uses: actions/checkout@v4
        with:
          repository: ${{ vars.GITOPS_REPO }}
          ref: ${{ vars.GITOPS_BRANCH }}
          token: ${{ secrets.GITOPS_REPO_TOKEN }}
          path: gitops

      - name: Update image tag in GitOps repository
        run: |
          cd gitops

          sed -i "s/tag: \".*\"/tag: \"$IMAGE_TAG\"/" clusters/dev/applications/argo-task-api.yaml

          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add clusters/dev/applications/argo-task-api.yaml
          git commit -m "chore: update task-api image tag to $IMAGE_TAG" || echo "No changes to commit"
          git push origin ${{ vars.GITOPS_BRANCH }}
